//! C backend.
//!
//! Lowers Lumen IR to portable C99 source. Used as a correctness oracle
//! (compile with `cc`, run, compare against `ndarray`) and as the fallback
//! path on platforms whose native backend isn't ready yet.
//!
//! Scope (Phase 2): function signatures with tensor parameters, matmul on
//! rank-2 f32 tensors, `Param`, `MatMul`, `Return`. Each Lumen function `f`
//! becomes a C function with the signature:
//!
//! ```c
//! void lumen_f(const float* p0, const float* p1, /* ... */ float* result);
//! ```
//!
//! Buffers are caller-owned, row-major, contiguous.

use lumen_ir::ty::{DType, Dim, TensorType};
use lumen_ir::{Function, IrModule, Op, ValueId};

#[derive(thiserror::Error, Debug)]
pub enum CBackendError {
    #[error("unsupported dtype {0:?} in C backend (Phase 2 scope)")]
    UnsupportedDType(DType),
    #[error("unsupported op {0} in C backend (Phase 2 scope)")]
    UnsupportedOp(&'static str),
    #[error("dynamic shape in C backend (Phase 2 requires static shapes)")]
    DynamicShape,
}

pub fn emit_module(m: &IrModule) -> Result<String, CBackendError> {
    let mut out = String::new();
    out.push_str("// Generated by Lumen. Do not edit.\n");
    out.push_str("#include <stddef.h>\n\n");
    for f in &m.functions {
        emit_function(&mut out, f)?;
        out.push('\n');
    }
    Ok(out)
}

fn emit_function(out: &mut String, f: &Function) -> Result<(), CBackendError> {
    // Signature.
    let mut sig = format!("void lumen_{}(", f.name);
    for (i, _pv) in f.param_values.iter().enumerate() {
        if i > 0 {
            sig.push_str(", ");
        }
        let ty = &f.params[i];
        sig.push_str(&format!("const {} *p{}", c_elem_type(ty.dtype)?, i));
    }
    sig.push_str(&format!(", {} *result) {{\n", c_elem_type(f.ret.dtype)?));
    out.push_str(&sig);

    // Find the unique return value's source.
    let ret_src = find_return_source(f).ok_or(CBackendError::UnsupportedOp("missing return"))?;

    emit_value_recursive(out, f, ret_src, "result")?;

    out.push_str("}\n");
    Ok(())
}

fn find_return_source(f: &Function) -> Option<ValueId> {
    for v in &f.values {
        if let Op::Return { value } = &v.op {
            return Some(*value);
        }
    }
    None
}

/// Emit C code that writes the result of value `id` into the buffer named `dst`.
/// Phase 2 supports very few op shapes: a parameter (memcpy), or a matmul of
/// two parameters. Anything else is rejected.
fn emit_value_recursive(
    out: &mut String,
    f: &Function,
    id: ValueId,
    dst: &str,
) -> Result<(), CBackendError> {
    let v = &f.values[id.0 as usize];
    match &v.op {
        Op::Param { index } => {
            let ty = &f.params[*index as usize];
            let n = numel(ty)?;
            out.push_str(&format!(
                "  for (size_t i = 0; i < {n}; ++i) {{ {dst}[i] = p{index}[i]; }}\n",
                n = n,
                dst = dst,
                index = index,
            ));
            Ok(())
        }
        Op::MatMul { lhs, rhs } => {
            let l_ty = f.type_of(*lhs).clone();
            let r_ty = f.type_of(*rhs).clone();
            let (m, k) = static_2d(&l_ty)?;
            let (_, n) = static_2d(&r_ty)?;
            // Both operands must be Param to keep Phase 2 simple.
            let l_idx = expect_param(&f.values[lhs.0 as usize].op)?;
            let r_idx = expect_param(&f.values[rhs.0 as usize].op)?;
            let elem = c_elem_type(l_ty.dtype)?;
            let body = format!(
                "  for (size_t i = 0; i < {m}; ++i) {{\n    for (size_t j = 0; j < {n}; ++j) {{\n      {elem} acc = ({elem})0;\n      for (size_t kk = 0; kk < {k}; ++kk) {{\n        acc += p{l_idx}[i * {k} + kk] * p{r_idx}[kk * {n} + j];\n      }}\n      {dst}[i * {n} + j] = acc;\n    }}\n  }}\n",
            );
            out.push_str(&body);
            Ok(())
        }
        Op::Return { .. } => Err(CBackendError::UnsupportedOp("nested return")),
        _ => Err(CBackendError::UnsupportedOp(
            "Phase 2 supports Param/MatMul only",
        )),
    }
}

fn expect_param(op: &Op) -> Result<u32, CBackendError> {
    match op {
        Op::Param { index } => Ok(*index),
        _ => Err(CBackendError::UnsupportedOp(
            "Phase 2 matmul operands must be raw function parameters",
        )),
    }
}

fn static_2d(t: &TensorType) -> Result<(u32, u32), CBackendError> {
    if t.shape.0.len() != 2 {
        return Err(CBackendError::UnsupportedOp("matmul operand not rank-2"));
    }
    match (&t.shape.0[0], &t.shape.0[1]) {
        (Dim::Static(a), Dim::Static(b)) => Ok((*a, *b)),
        _ => Err(CBackendError::DynamicShape),
    }
}

fn numel(t: &TensorType) -> Result<u64, CBackendError> {
    let mut n: u64 = 1;
    for d in &t.shape.0 {
        match d {
            Dim::Static(v) => n *= *v as u64,
            Dim::Dynamic(_) => return Err(CBackendError::DynamicShape),
        }
    }
    Ok(n)
}

fn c_elem_type(d: DType) -> Result<&'static str, CBackendError> {
    match d {
        DType::F32 => Ok("float"),
        DType::F16 => Err(CBackendError::UnsupportedDType(d)), // Phase 5
        DType::I32 => Ok("int32_t"),
        DType::Q4_0 | DType::Q8_0 => Err(CBackendError::UnsupportedDType(d)), // Phase 5
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use lumen_dsl::Parser;
    use lumen_ir::lower;

    #[test]
    fn emits_matmul_c() {
        let src = r#"
            fn matmul(
                a: tensor<f32, [4, 5]>,
                b: tensor<f32, [5, 3]>,
            ) -> tensor<f32, [4, 3]> {
                return a @ b;
            }
        "#;
        let ast = Parser::parse(src).unwrap();
        let ir = lower(&ast).unwrap();
        let c = emit_module(&ir).unwrap();
        assert!(c.contains("void lumen_matmul"));
        assert!(c.contains("const float *p0"));
        assert!(c.contains("const float *p1"));
        assert!(c.contains("float *result"));
        // Triple loop dimensions.
        assert!(c.contains("i < 4"));
        assert!(c.contains("j < 3"));
        assert!(c.contains("kk < 5"));
    }
}
